language: perl
perl:
  - "5.22"
  - "5.14"
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
env:
  global:
    secure: "sr30uuXSQ9FwucuDzz2x3YOfO7xfK5mStXDEfitFVFruXmrebJfNkBdYORa++9IuwSCOxC20HOtFCqV55pHrhRbTxdmYC9U5RRmrFfxFLwSyTEp4C3LAo5pQ+nW1fBSE7fw/uxgaU6Ij0tbXmoSve8fpHBU/ytn1cA0SdPqOtoA="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
